version: "3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgresdev"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pruebas
    user: root
    ports:
      - "5432:5432"
    #volumes:
    #  - ./Scripts/Cargas/Postgres:/var/lib/postgresql/data
  # uncomment initdb if you need initdb at first run
  initdb:
    build: .
    image: ownquipux
    entrypoint: alembic upgrade head
    container_name: 'initdbd'
    user: root
    depends_on:
      - postgres

  publisher:
    build: .
    image: ownquipux
    container_name: 'publisher'
    user: root
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./Dags:/usr/local/airflow/Dags
      - ./Scripts/Cargas/Logs/Airflow:/usr/local/airflow/Logs/Airflow
      - ./Scripts/Cargas/Logs/Logger:/usr/local/airflow/Logs/Logger
      - ./LibreriasGlobales:/usr/local/airflow/LibreriasGlobales/BigData
      - ./Scripts/Cargas/Config/Properties:/usr/local/airflow/Properties
      - ./Scripts/Cargas/Librerias:/usr/local/airflow/Cargas/Librerias
      - ./Scripts/Cargas/Sql:/usr/local/airflow/Cargas/Sql
    entrypoint: python publisher

  worker:
    build: .
    image: ownquipux
    container_name: 'worker'
    user: root
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./Dags:/usr/local/airflow/Dags
      - ./Scripts/Cargas/Logs/Airflow:/usr/local/airflow/Logs/Airflow
      - ./Scripts/Cargas/Logs/Logger:/usr/local/airflow/Logs/Logger
      - ./LibreriasGlobales:/usr/local/airflow/LibreriasGlobales/BigData
      - ./Scripts/Cargas/Config/Properties:/usr/local/airflow/Properties
      - ./Scripts/Cargas/Librerias:/usr/local/airflow/Cargas/Librerias
      - ./Scripts/Cargas/Sql:/usr/local/airflow/Cargas/Sql
    entrypoint: python subscriptor

  


